create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar (255) NOT NULL,
    email varchar(512) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    requestor_id BIGINT NOT NULL references users (id),
    created timestamp
);

create TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    is_available bool,
    owner_id BIGINT NOT NULL references users (id) on delete cascade,
    request_id BIGINT references requests(id)
);

create TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date timestamp,
    end_date timestamp,
    item_id BIGINT NOT NULL references items (id),
    booker_id BIGINT NOT NULL references users (id),
    status varchar (100)
);

create TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    item_id BIGINT NOT NULL references items (id),
    author_id BIGINT NOT NULL references users (id),
    created timestamp
);